#!/bin/sh
#dashboardLauncher.sh
#Navitage to directoyr, then execute

#export PYTHONPATH=/usr/local/lib/python2.7/dist-packages:$PYTHONPATH

#/user/bin/python2.7 


cd /home/pi/ichnaeagit/qtdesigner

/home/pi/ichnaeagit/qtdesigner/prepDesignFile.sh

sudo python runGUI.py

